2.Modules/MPLIS.Modules.XuLyHoSo/Controllers/TTBienDongController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using AppCore.Models;
using System.IO;
using System.Net;
using MPLIS.Web.FrameWork.Base;
using MPLIS.Libraries.Services.XuLyHoSo.Classes;
using MPLIS.Libraries.Data.XuLyHoSo.Models;
using System.Globalization;
using Newtonsoft.Json;
using System.Data.Common;
using AutoMapper;
using System.Reflection;

namespace MPLIS.Modules.XuLyHoSo.Controllers
{
    public class TTBienDongController : BaseController
    {
        #region Biến Động HieuVH2
        [HttpPost]
        public ActionResult KiemTraBienDong()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            if (bhs.HoSoTN.BienDong == null)
            {
                bhs.HoSoTN.CurBienDong = new DC_BIENDONG();
                DC_BIENDONG bienDong = bhs.HoSoTN.CurBienDong;
                bienDong.BIENDONGID = Guid.NewGuid().ToString();
                bienDong.HOSOTIEPNHANID = bhs.HoSoTN.HOSOTIEPNHANID;
                Session["BoHoSo_" + CurrentUser.UserName] = bhs;
                return Json(new { exist = false, mes = "Cần tạo mới thông tin cho Biến Động!" });
            }
            return Json(new { exist = true });
        }
        public ActionResult BienDong_ThemMoi_TTChung()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            TTChungBienDongVM bd = Mapper.Map<DC_BIENDONG, TTChungBienDongVM>(bhs.HoSoTN.CurBienDong);
            ViewBag.DM_LOAIBIENDONG_list = new SelectList(bhs.DS_LoaiBienDong, "LOAIBIENDONGID", "TENLOAIBIENDONG");
            return PartialView(bd);
        }
        [HttpPost]
        public ActionResult BienDong_ThemMoi_Save(TTChungBienDongVM formData)
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            bhs.HoSoTN.BienDong = Mapper.Map<TTChungBienDongVM, DC_BIENDONG>(formData);
            bhs.HoSoTN.BienDong.LOAIBIENDONGID = "444444";
            bhs.HoSoTN.BienDong.DSGcn = new List<DC_BD_GCN>();
            bhs.HoSoTN.BienDong.DSChu = new List<DC_BD_CHU>();
            bhs.HoSoTN.BienDong.DSThua = new List<DC_BD_THUA>();
            bhs.HoSoTN.CurBienDong = null;
            DCBIENDONGServices.SaveBienDong(bhs.HoSoTN.BienDong);
            Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return Json(new { success = true, mes = "Thêm mới Biến Động thành công!" });
        }
        #region Giấy Chứng Nhận
        public ActionResult BienDong_DSGCN()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            DSGCNBDVM GCNVM = new DSGCNBDVM();
            GCNVM.initData(bhs);
            return PartialView(GCNVM);
        }
        public ActionResult BienDong_DSGCNVAO()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            DSGCNBDVM GCNVM = new DSGCNBDVM();
            GCNVM.initData(bhs);
            return PartialView(GCNVM);
        }
        public ActionResult BienDong_DSGCNRA()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            DSGCNBDVM GCNVM = new DSGCNBDVM();
            GCNVM.initData(bhs);
            return PartialView(GCNVM);
        }
        [HttpPost]
        public ActionResult BienDong_DSGCN_XoaGCN(string bienDongGCNID)
        {
            bool success = false;
            string message = "";
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            if (DCBDGCNServieces.XoaBDGCN(bienDongGCNID, bhs, out message))
            {
                Session["BoHoSo_" + CurrentUser.UserName] = bhs;
                success = true;
            }
            return Json(new { success = success, message = message });
        }
        [HttpPost]
        public ActionResult BienDong_DSGCNVAO_SaoChepGCN(string bienDongGCNID)
        {
            bool success = false;
            string message = "";
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            if(success = DCBDGCNServieces.SaoChepBDGCN(bienDongGCNID, bhs, out message))
                Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return Json(new { success = success, message = message });
        }
        [HttpPost]
        public ActionResult ThemMoi_GCN(string LAGCNVAO)
        {
            bool success = false;
            string message = "";
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            if (success = DCBDGCNServieces.ThemMoiBDGCN(LAGCNVAO, bhs, out message))
                Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return Json(new { success = success, message = message });
        }
        [HttpPost]
        public ActionResult ThemMoi_GCNVao_TuDangKy()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            DSGCNDonVM dSGCNDonVM = new DSGCNDonVM();
            foreach (var temp in bhs.HoSoTN.DonDangKy.DSDangKyGCN)
                dSGCNDonVM.DSDangKyGCN.Add(Mapper.Map<DC_DANGKY_GCN, GCNDonVM>(temp));
            return PartialView("Popup_DSGCNDangKy", dSGCNDonVM);
        }
        [HttpPost]
        public ActionResult BienDong_Save_DSGCN(string data)
        {
            bool success = false;
            string message = "";
            Hashtable hashTable = JsonConvert.DeserializeObject<Hashtable>(data);
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            DCGIAYCHUNGNHANServices.ConvertHashTableToDSGCNCha(hashTable, bhs.HoSoTN.BienDong.DSGcn);
            return Json(new { success = success, message = message });
        }
        #endregion
        //Tham số truyền vào chuỗi data được JSON.stringify từ List<DANGKYGCNID>
        [HttpPost]
        public ActionResult SaveForm_Popup_DSGCNDangKy(string data)
        {
            bool success = false;
            string message = "";
            List<string> dSDANGKYGCNID = JsonConvert.DeserializeObject<List<string>>(data);
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            if (DCBDGCNServieces.ThemMoiBDGCNTuDangKy(dSDANGKYGCNID, bhs, out message))
            {
                Session["BoHoSo_" + CurrentUser.UserName] = bhs;
                success = true;
            }
            return Json(new { success = success, message = message });
        }
        #endregion
        //GET: TTBienDong
        public ActionResult Index()
        {
            return PartialView();
        }

        #region "Load data - for each partial view"
        public ActionResult _HoSoTiepNhan()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            //XuLyHoSoController xuLyHoSo = new XuLyHoSoController();
            //return PartialView("")
            ////Lưu lịch sử
            //QT_HOSOTIEPNHAN HSTN = QTHOSOTIEPNHANServices.getAllHoSoTiepNhan("da67d46d-621c-4e4e-89c3-758f949adf64"); //hồ sơ test lưu lịch sử
            ////QT_HOSOTIEPNHAN HSTN = QTHOSOTIEPNHANServices.getAllHoSoTiepNhan("2D921A9AF541474991F4380FAE31561F");   //hồ sơ Trường test
            //HoSoTiepNhanLS HoSoLS = BOHOSOServices.ConvertHoSoTiepNhanToLS(HSTN);
            //QT_HOSOTIEPNHAN HSTN1 = BOHOSOServices.ConvertHoSoLSToHoSoTiepNhan(HoSoLS);
            //BOHOSOServices.LuuLichSu(HSTN);

            ////Khôi phục dữ liệu
            //LS_BOHOSO bhs = BOHOSOServices.getHoSoLSByBienDongID("C3D9ADCCEAD046D593ACB353C5CEBF6D");
            //HoSoTiepNhanLS HoSoLS1 = JsonConvert.DeserializeObject<HoSoTiepNhanLS>(bhs.DATA);
            //BOHOSOServices.RestoreBussinessData(bhs);

            //BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            //ViewBag.DSLoaiHoSo
            ViewBag.DSLoaiHoSo = new SelectList(new List<SelectListItem>
            {
                new SelectListItem() {Selected = false, Text = "Trực tiếp", Value = "0" },
                new SelectListItem() {Selected = false, Text = "Trực tuyến", Value = "1" },
                new SelectListItem() {Selected = false, Text = "Nơi khác", Value = "2" }
            }, "LOAIHOSO", "TENLOAI");
            ViewBag.DSVaiTroNguoiNop = new SelectList(new List<SelectListItem>
            {
                new SelectListItem() {Selected = false, Text = "Chủ sử dụng / sở hữu", Value = "1" },
                new SelectListItem() {Selected = false, Text = "Người được ủy quyền", Value = "2" },
                new SelectListItem() {Selected = false, Text = "Điều kiện thửa kê khai trình", Value = "3" }
            }, "VAITRONGUOINOPHOSO", "TENVAITRO");
            ViewBag.DSPhuongPhapNhanThongBao = new SelectList(new List<SelectListItem>
            {
                new SelectListItem() {Selected = false, Text = "Trực tiếp", Value = "0" },
                new SelectListItem() {Selected = false, Text = "Tin nhắn SMS", Value = "1" },
                new SelectListItem() {Selected = false, Text = "Email", Value = "2" },
                new SelectListItem() {Selected = false, Text = "Tổng đài điện thoại", Value = "3" },
                new SelectListItem() {Selected = false, Text = "Trực tiếp + SMS", Value = "4" },
                new SelectListItem() {Selected = false, Text = "Trực tiếp + SMS + Email", Value = "5" },
                new SelectListItem() {Selected = false, Text = "Trực tiếp + SMS + Email + Tổng đài", Value = "6" }
            }, "PHUONGPHAPNHANTHONGBAO", "TENPHUONGPHAP");
            return PartialView("~/Views/XuLyHoSo/_XLHS_HoSoTiepNhan.cshtml", bhs.HoSoTN);
        }

        public ActionResult _ThongTinDangKy()
        {
            return PartialView();
        }

        public ActionResult _BienDong()
        {

2.Modules/MPLIS.Modules.XuLyHoSo/Views/TTBienDong/_BienDong.cshtml
<div id="divBienDongID" class="m-15">
    <div class="row panel" style="margin-bottom: 5px;">
        <div class="btn btn-default btn-block tab-doc" style="text-align:left;">
            <a style="color: blue;font-weight: bold;" data-toggle="collapse" data-parent="#divBienDongID" href="#collapse_BienDong_BD">
                Thông tin chung biến động
            </a>
            <button class="btn-xs btn-heading pull-right" type="button" onclick="PheDuyet_BD()">Phê duyệt</button>
            <button class="btn-xs btn-heading pull-right" type="button" onclick="LuuBienDong_BD()">Lưu thông tin</button>
            <button id="btn_ThongTinRieng_BDID" class="btn-xs btn-heading pull-right" type="button" onclick="ThongTinRieng_BD()">Thông tin riêng BD</button>
        </div>
        <div id="collapse_BienDong_BD" class="panel-collapse collapse in">
            <div id="divBienDongID_BD">
                @Html.Action("_BienDong_BD", "TTBienDong")
            </div>
        </div>
    </div>
    <div class="row panel" style="margin-bottom: 5px;">
        <div class="btn btn-default btn-block tab-doc" style="text-align:left;">
            <a style="color: blue;font-weight: bold;" data-toggle="collapse" data-parent="#divBienDongID" href="#collapse_BienDong_DSGCN">
                Danh sách GCN tham gia biến động
            </a>
            <button type="button" onclick="LuuBienDong_DSGCN()" class="btn-xs btn-heading pull-right">Lưu vào CSDL</button>
        </div>
        <div id="collapse_BienDong_DSGCN" class="panel-collapse collapse">
            <div id="divBienDongID_DSGCN" class="partialContents" data-url="/TTBienDong/BienDong_DSGCN">
            </div>
        </div>
    </div>
    <div class="row panel" style="margin-bottom: 5px;">
        <div class="btn btn-default btn-block tab-doc" style="text-align:left;">
            <a style="color: blue;font-weight: bold;" data-toggle="collapse" data-parent="#divBienDongID" href="#collapse_BienDong_DSTHUA">
                Danh sách thửa tham gia biến động
            </a>
            <button type="button" onclick="LuuBienDong_DSTHUA()" class="btn-xs btn-heading pull-right" style="margin-right:5px;">Lưu vào CSDL</button>
            <button type="button" onclick="LamMoiDanhSachThua()" class="btn-xs btn-heading pull-right" style="margin-left:5px;">Làm mới danh sách</button>
        </div>
        <div id="collapse_BienDong_DSTHUA" class="panel-collapse collapse">
            <div id="divBienDongID_DSTHUA" class="partialContents" data-url="/TTBienDong/_BienDong_DSTHUA">
            </div>
        </div>
    </div>
    <div id="div_BienDong_TTRIENG_ID" class="row panel" style="margin-bottom: 5px;">
        <div class="btn btn-default btn-block tab-doc" style="text-align:left;">
            <a style="color: blue;font-weight: bold;" data-toggle="collapse" data-parent="#divBienDongID" href="#collapse_BienDong_TTRIENG">
                Thông tin riêng
            </a>
            <button type="button" onclick="LuuBienDong_TTRIENG()" class="btn-xs btn-heading pull-right">Lưu vào CSDL</button>
        </div>
        <div id="collapse_BienDong_TTRIENG" class="panel-collapse collapse">
            <div id="divBienDongID_TTRIENG" class="partialContents" data-url="/TTBienDong/_BienDong_TTRIENG">
            </div>
        </div>
    </div>
</div>

<div id="divPopupID">

</div>

<div id="dialogformQuyetDinhID">
    @*@{Html.RenderPartial("_PopupQuyetDinh");}*@
</div>

<div id="dialogformDSQuyetDinhID">
    @*@{Html.RenderPartial("_PopupQuyetDinh");}*@
</div>

<div id="dialogformDSCHUVAOID">
    @*@{Html.RenderPartial("_Popup_DSCHUVAO", Model);}*@
</div>

<div id="dialogformDSGCNRAID">
    @*@{Html.RenderPartial("_Popup_DSGCNRA");}*@
</div>

<div id="dialogformDSGCNVAOID">
    @*@{Html.RenderPartial("_Popup_DSGCNVAO");}*@
</div>

<div id="dialogformDSTHUARAID">
    @*@{Html.RenderPartial("_Popup_DSTHUARA");}*@
</div>

<div id="dialogformDSTHUAVAOID">
    @*@{Html.RenderPartial("_Popup_DSTHUAVAO");}*@
</div>

<div id="dialogformDSTHUAXLID">
    @*@{Html.RenderPartial("_Popup_DSTHUAXL");}*@
</div>

<script type="text/javascript">
    function LuuBienDong_BD() {
        $.ajax({
            type: "POST",
            url: "/TTBienDong/Save_IDformBienDong_BD",
            data: $('#IDformBienDong_BD').serialize(),
            success: function (html) {
                alert("Lưu biến động thành công!");
            },
        });
    };

    //function LuuBienDong_DSGCN() {
    //    var dt = document.getElementById("JSONCha").value;
    //    $.ajax({
    //        type: "POST",
    //        url: "/TTBienDong/Save_IDformBienDong_DSGCN",
    //        data: { JsonGcnCha: dt },
    //        success: function (html) {
    //            alert("Lưu danh sách GCN thành công!");
    //        },
    //    });
    //};

    function LuuBienDong_DSGCN() {
        $.ajax({
            type: "POST",
            url: "/TTBienDong/BienDong_Save_DSGCN",
            data: { data: $('#JSONCha').val() },
            dataType: "json",
            success: function (result) {
                alert(result.mes);
            }
        })
    }

    function LuuBienDong_DSTHUA() {
        //console.log('Thua data:' + formBienDong_DSTHUA.serialize());
        var dt = document.getElementById("JSONThuaCha").value;
        var CoThuaXuLy = $('#isCOTHUAXL').is(':checked');
        console.log('CoThuaXuLy:' + CoThuaXuLy);
        console.log('Thua cha:' + dt);
        $.ajax({
            type: "POST",
            url: "/TTBienDong/Save_IDformBienDong_DSTHUA",
            data: { JSONThuaCha: dt, isCOTHUAXL: CoThuaXuLy },
            success: function (html) {
                console.log(html);
                $('#divBienDongID_DSTHUA').html(html);
                alert("Lưu danh sách thửa thành công!");
            },
        });
    };

    function LamMoiDanhSachThua() {
        $.ajax({
            type: "POST",
            url: "/TTBienDong/_BienDong_UpdateDSTHUA",
            success: function (html) {
                $('#divBienDongID_DSTHUA').html(html);
                console.log(html);
            },
        });
    };

    var formBienDong_TTRIENG = $('#IDformBienDong_TTRIENG');
    function LuuBienDong_TTRIENG() {
        $.ajax({
            type: "POST",
            url: "/TTBienDong/Save_IDformBienDong_TTRIENG",
            data: formBienDong_TTRIENG.serialize(),
            success: function (html) {
                $('#divBienDongID_TTRIENG').html(html);
                alert("Lưu TT riêng thành công");
            },
        });
    };

    $(document).ready(function () {
        //kích hoạt sự kiện trên các tab dọc
        trigger_tab_doc();

        var ckcottrienghaykord = $('#ListLoaibiendongid').val();
        $(".partialContents").each(function (index, item) {
            var url = $(item).data("url");
            if (url && url.length > 0) {
                if (url.indexOf("/TTBienDong/_BienDong_TTRIENG") == -1) {
                    $(item).load(url, function (responseTxt, statusTxt, xhr) {
                        console.log('Load data-url' + url);
                    });
                }
                else if (ckcottrienghaykord == "444444" || ckcottrienghaykord == "45555555") {
                    $(item).load(url, function (responseTxt, statusTxt, xhr) {
                        console.log('Load data-url' + url);
                    });
                }
            }
        });
    })
</script>

2.Modules/MPLIS.Modules.XuLyHoSo/Views/TTBienDong/_BienDong_DSCHU.cshtml
@model MPLIS.Libraries.Data.XuLyHoSo.Models.DSChuBDVM

<form id="IDformBienDong_DSCHU">
    <div>
        <div id="divBienDongID_DSCHUVAO">
            @{Html.RenderPartial("_BienDong_DSCHUVAO", Model);}
        </div>
        <div id="divBienDongID_DSCHURA">
            @{Html.RenderPartial("_BienDong_DSCHURA", Model);}
        </div>
    </div>
</form>

2.Modules/MPLIS.Modules.XuLyHoSo/Views/TTBienDong/_BienDong_DSCHUVAO_Table.cshtml
@model MPLIS.Libraries.Data.XuLyHoSo.Models.DSChuBDVM

<table id="table_DSCHUVAOID" class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Vai trò chủ</th>
            <th>Loại chủ</th>
            <th>Họ tên</th>
            <th>CMT/Hộ chiếu</th>
            <th></th>
        </tr>
    </thead>
    @{int rowdsChuVaoID = 0;
        if (Model.DSChu != null)
        {
            foreach (var item in Model.DSChu)
            {
                rowdsChuVaoID = rowdsChuVaoID + 1;
                <tr data-id="@item.NGUOIID">
                    <td style="text-align: right;">
                        @rowdsChuVaoID.
                    </td>
                    <td>
                        @item.VaiTro
                    </td>
                    <td>
                        @item.Chu_TenLoaiChu
                    </td>
                    <td>
                        @item.Chu_HoTen
                    </td>
                    <td>
                        @item.Chu_CMT
                    </td>
                    <td style="text-align: center;">
                        @Ajax.ActionLink("Xóa", "Remove_DSCHUVAO_R", "TTBienDong", new { id = item.NGUOIID },
                            new AjaxOptions
                            {
                                HttpMethod = "POST",
                                //OnSuccess = "RemoveRow",
                                UpdateTargetId = "divBienDongID_DSCHUVAO_Table",
                                InsertionMode = InsertionMode.Replace,
                                Confirm = "Xác nhận xóa?"
                            }, new { @class = "btn btn-xs btn-heading", @title = "Xóa" })
                        @Ajax.ActionLink("Chi tiết", "Details_DSCHUVAO_R", "TTBienDong", new { id = item.NGUOIID },
                            new AjaxOptions
                            {
                                HttpMethod = "POST",
                                OnSuccess = "alert('Demo!')",
                                UpdateTargetId = "divBienDongID_DSCHUVAO_Table",
                                InsertionMode = InsertionMode.Replace
                            }, new { @class = "btn btn-xs btn-heading", @title = "Chi tiết" })
                    </td>
                </tr>
            }
        }
    }
</table>
<script type="text/javascript">
    $(document).ready(function () {
        InitDataTableXLHS($('#table_DSCHUVAOID'));
    });
</script>

2.Modules/MPLIS.Modules.XuLyHoSo/Views/TTBienDong/_BienDong_DSGCNVAO.cshtml
@model MPLIS.Libraries.Data.XuLyHoSo.Models.DSGCNBDVM

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Danh sách GCN đầu vào</h3>
        <button class="btn-xs btn-heading pull-right" type="button" onclick="ThemTuDangKy()">Thêm từ đăng ký</button>
        <button class="btn-xs btn-heading pull-right" type="button" onclick="ThemMoi()">Thêm mới</button>
    </div>
    <div class="box-body">
        <table id="table_DSGCNVAOID" class="table table-bordered">
            <thead>
                <tr>
                    <th>Là cha</th>
                    <th>#</th>
                    <th>Số phát hành</th>
                    <th>Mã vạch</th>
                    <th>Trạng thái</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.DSGcn != null && Model.DSGcn.Count() > 0)
                {
                    int rowdsGCNVaoID = 0;
                    foreach (var item in Model.DSGcn)
                    {
                        if (item.LAGCNVAO == "Y")
                        {
                            rowdsGCNVaoID = rowdsGCNVaoID + 1;
                            <tr data-id="@item.GIAYCHUNGNHANID">
                                <td class="text-center">
                                    <input type="checkbox" name="Array_DSGCNCHA" id="@item.GIAYCHUNGNHANID" value="@item.GIAYCHUNGNHANID"
                                           onclick="calc(@item.GIAYCHUNGNHANID);" />
                                </td>
                                <td class="text-right">
                                    @rowdsGCNVaoID.
                                </td>
                                <td class="text-center">
                                    @item.SoPhatHanh
                                </td>
                                <td class="text-center">
                                    @item.MaVach
                                </td>
                                <td class="text-center">
                                    @item.TrangThai
                                </td>
                                <td class="text-center">
                                    @Ajax.ActionLink("Xóa", "Remove_DSGCNVAO_R", "TTBienDong", new { id = item.BDGCNID },
                                    new AjaxOptions
                                    {
                                        HttpMethod = "POST",
                                        //OnSuccess = "RemoveRow",
                                        UpdateTargetId = "divBienDongID_DSGCN",
                                        InsertionMode = InsertionMode.Replace
                                    }, new { @class = "btn btn-xs btn-heading", @title = "Xóa" })
                                    @Ajax.ActionLink("Sao chép", "Copy_DSGCNVAO_R", "TTBienDong", new { id = item.BDGCNID },
                                    new AjaxOptions
                                    {
                                        HttpMethod = "POST",
                                        OnSuccess = "Load_TTRIENG_THECHAP_CTQUYEN()",
                                        UpdateTargetId = "divBienDongID_DSGCN",
                                        InsertionMode = InsertionMode.Replace
                                    }, new { @class = "btn btn-xs btn-heading btncoppy", @title = "Copy tới đầu ra" })
                                    @Ajax.ActionLink("Chi tiết", "_GiayChungNhan", "XLHSGiayChungNhan", new { id = item.GIAYCHUNGNHANID, loaiGCN = 1 },
                                    new AjaxOptions
                                    {
                                        HttpMethod = "POST",
                                        //OnSuccess = "RemoveRow",
                                        UpdateTargetId = "bhs-tabID",
                                        InsertionMode = InsertionMode.Replace
                                    }, new { @class = "btn btn-xs btn-heading", @title = "Chi tiết thông tin GCN" })
                                </td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    function ThemTuDangKy() {
        $.ajax({
            type: "GET",
            url: "/TTBienDong/_Popup_DSGCNDangKy",
            success: function (html) {
                $('#dialogformDSGCNVAOID').html(html);
                var options = {
                    "backdrop": "static",
                    "show": true
                }
                $("#modalformDSGCNVAOID").modal(options);
            },
        });
        //return false;
    }

    function ThemMoi() {
        $.ajax({
            type: "GET",
            url: "/TTBienDong/ThemMoiGiayChungNhanVao",
            success: function (html) {
                console.log(html);
                $('#divBienDongID_DSGCNVAO').html(html);
            },
        });
        return false;
    }

    $("#table_DSGCNVAOID input").change(function () {
        var id = document.getElementById("CurGCNRaID").value;
        //console.log("CurGCNRaID:" + id);
        if (id && id != "") {
            var data = document.getElementById("JSONCha").value;
            //console.log("json value:" + data);
            var obj = JSON.parse(data);
            //console.log("json array:" + obj[id]);
            var arr = obj[id];
            var GCNID = this.id;
            var index = arr.indexOf(GCNID);
            if ($(this).is(':checked')) {
                //console.log("GCNID:" + GCNID);
                if (index == -1) arr.push(GCNID);
            } else {
                if (index > -1) arr.splice(index, 1);
            }
            obj[id] = arr;
            document.getElementById("JSONCha").value = JSON.stringify(obj);
        } else alert('Bạn cần chọn một giấy chứng nhận đầu ra trước');
    });

    $(document).ready(function () {
        InitDataTableXLHS($('#table_DSGCNVAOID'));
    })
</script>

2.Modules/MPLIS.Modules.XuLyHoSo/Views/TTBienDong/_BienDong_TTRIENG.cshtml
@model MPLIS.Libraries.Data.XuLyHoSo.Models.TTRiengVM
<div id="divBienDongID_DSCHUVAO">
    @*@{Html.RenderPartial("_BienDong_DSCHUVAO", Model.dSChuBDVM);}*@
</div>
<div id="divBienDongID_TTRIENG_THECHAP">
    @*@{Html.RenderPartial("_BienDong_TTRIENG_THECHAP", Model.theChapVM);}*@
</div>
<div id="divBienDongID_TTRIENG_THECHAP_CTQUYEN">
    @*@{Html.RenderPartial("_BienDong_TTRIENG_THECHAP_TTQUYEN");}*@
</div>

2.Modules/MPLIS.Modules.XuLyHoSo/Views/TTBienDong/_TTNghiaVuTaiChinh.cshtml
chưa làm