2.Modules/MPLIS.Modules.XuLyHoSo/Controllers/XLHSGiayChungNhanController.cs
using AppCore.Models;
using MPLIS.Libraries.Data.XuLyHoSo.Models;
using MPLIS.Libraries.Services.XuLyHoSo.Classes;
using MPLIS.Web.FrameWork.Base;
using System;
using System.IO;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MPLIS.Modules.XuLyHoSo.Controllers
{
    public class XLHSGiayChungNhanController : BaseController
    {
        #region Giấy Chứng Nhận
        [HttpPost]
        public ActionResult InitCurGiayChungNhan(string gCNID, TaiGCN taiGCN)
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            if (DCGIAYCHUNGNHANServices.InitBHSCurGCN(gCNID, taiGCN, bhs))
            {
                Session["BoHoSo_" + CurrentUser.UserName] = bhs;
                return PartialView("GiayChungNhan");
            }
            return Json(new { message = "Dữ liệu không đúng?" });
        }
        [HttpPost]
        public ActionResult GiayChungNhan(string iD, TaiGCN loaiGCN)
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            bhs.initCurGCN(iD, loaiGCN);
            Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return PartialView();
        }
        public ActionResult GiayChungNhan_Main()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            GiayChungNhanLS giayChungNhanLS = Mapper.Map<DC_GIAYCHUNGNHAN, GiayChungNhanLS>(bhs.CurDC_GIAYCHUNGNHAN);
            ViewBag.dSTrangThaiXL = new SelectList(new List<SelectListItem>
            {
                new SelectListItem() {Selected = true, Text = "-- Chọn trạng thái xử lý --", Value = "" },
                new SelectListItem() {Selected = false, Text = "Đã phê duyệt, có tính pháp lý", Value = "Y" },
                new SelectListItem() {Selected = false, Text = "Không được phê duyệt, không có tính pháp lý", Value = "N" },
                new SelectListItem() {Selected = false, Text = "Đang xử lý, không có tính pháp lý", Value = "S" }
            }, "Value", "Text");
            Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return PartialView(giayChungNhanLS);
        }
        public ActionResult GiayChungNhan_Main_HanChe()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            GiayChungNhanLS giayChungNhanLS = Mapper.Map<DC_GIAYCHUNGNHAN, GiayChungNhanLS>(bhs.CurDC_GIAYCHUNGNHAN);
            return PartialView(giayChungNhanLS);
        }
        public ActionResult GiayChungNhan_Main_QLDat()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            GiayChungNhanLS giayChungNhanLS = Mapper.Map<DC_GIAYCHUNGNHAN, GiayChungNhanLS>(bhs.CurDC_GIAYCHUNGNHAN);
            return PartialView(giayChungNhanLS);
        }
        public ActionResult GiayChungNhan_Main_SDDat()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            GiayChungNhanLS giayChungNhanLS = Mapper.Map<DC_GIAYCHUNGNHAN, GiayChungNhanLS>(bhs.CurDC_GIAYCHUNGNHAN);
            return PartialView(giayChungNhanLS);
        }
        public ActionResult GiayChungNhan_Main_SHTaiSan()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            GiayChungNhanLS giayChungNhanLS = Mapper.Map<DC_GIAYCHUNGNHAN, GiayChungNhanLS>(bhs.CurDC_GIAYCHUNGNHAN);
            return PartialView(giayChungNhanLS);
        }
        [HttpPost]
        public ActionResult GiayChungNhan_Main_TLSH()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            GiayChungNhanLS giayChungNhanLS = Mapper.Map<DC_GIAYCHUNGNHAN, GiayChungNhanLS>(bhs.CurDC_GIAYCHUNGNHAN);
            return PartialView(giayChungNhanLS);
        }
        [HttpPost]
        public ActionResult Save_FormTTChungGCN(string data)
        {
            bool success = false;
            string message = "";
            try
            {
                GiayChungNhanLS giayChungNhanLS = JsonConvert.DeserializeObject<GiayChungNhanLS>(data);
                DC_GIAYCHUNGNHAN giayChungNhan = Mapper.Map<GiayChungNhanLS, DC_GIAYCHUNGNHAN>(giayChungNhanLS);
                BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
                if (DCGIAYCHUNGNHANServices.UpdateTTGiayChungNhan(giayChungNhan, bhs, out message))
                {
                    Session["BoHoSo_" + CurrentUser.UserName] = bhs;
                    success = true;
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            return Json(new { success = success, message = message });
        }
        [HttpPost]
        public ActionResult DanhSachHanChe_ChiTietHanChe(string hanCheID)
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            HanCheLS hanCheVM = null;
            foreach (var hanChe in bhs.CurDC_GIAYCHUNGNHAN.DSHanChe)
            {
                if (hanChe.HANCHEID == hanCheID)
                {
                    hanCheVM = Mapper.Map<DC_HANCHE, HanCheLS>(hanChe);
                    break;
                }
            }
            ViewBag.dSLoaiHanChe = DCTHUADATServices.get_Loaihanche();
            Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return PartialView("HanChe_ChiTiet", hanCheVM);
        }
        [HttpPost]
        public ActionResult DanhSachHanChe_ThemMoiHanChe()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            if (bhs.CurDC_GIAYCHUNGNHAN.ChinhSua)
            {
                ViewBag.dSLoaiHanChe = DCTHUADATServices.get_Loaihanche();
                return PartialView("HanChe_ChiTiet", Mapper.Map<DC_HANCHE, HanCheLS>(new DC_HANCHE()));
            }
            return Json(new { message = "Dữ liệu không đúng?" });
        }
        [HttpPost]
        public ActionResult HanChe_ChiTiet_SaveForm(string data)
        {
            bool success = false;
            string message = "";
            try
            {
                DC_HANCHE hanChe = JsonConvert.DeserializeObject<DC_HANCHE>(data);
                BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
                if (success = DCHANCHEServices.DBInsertOrUpdateHanChe_GCN(hanChe, out message, bhs))
                    Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            return Json(new { success = success, message = message });
        }
        [HttpPost]
        public ActionResult DanhSachHanChe_XoaHanChe(string hanCheID)
        {
            bool success = false;
            string message = "";
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            if (success = DCHANCHEServices.DBDeleteHanChe(hanCheID, bhs, out message))
                Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return Json(new { success = success, message = message });
        }
        #endregion
        #region "Popup"
        [HttpPost]
        public ActionResult Popup_ThemQuyenVaoGCN(QUYENTRENGCN iSQuyen)
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            DC_GIAYCHUNGNHAN curGiayChungNhan = bhs.CurDC_GIAYCHUNGNHAN;
            if (curGiayChungNhan.ChinhSua)
            {
                if (iSQuyen == QUYENTRENGCN.QSDDAT || iSQuyen == QUYENTRENGCN.QQLDAT)
                {
                    ViewBag.Title = iSQuyen == QUYENTRENGCN.QSDDAT ? "Thêm Quyền Sử Dụng Đất" : "Thêm Quyền Quản Lý Đất";
                    DSThuaDatVM dSThuaDatVM = new DSThuaDatVM();
                    dSThuaDatVM.ISQuyen = iSQuyen;
                    dSThuaDatVM.InitData(bhs);
                    return PartialView("Popup_DSThua", dSThuaDatVM);
                }
                else if (iSQuyen == QUYENTRENGCN.QSHTS)
                {
                    DSTaiSanVM dSTaiSan = new DSTaiSanVM();
                    dSTaiSan.ISQuyen = iSQuyen;
                    dSTaiSan.InitData(bhs);
                    return PartialView("Popup_DSTaiSan", dSTaiSan);
                }
            }
            return Json(new { message = "Dữ liệu không đúng?" });
        }
        [HttpPost]
        public ActionResult Save_Popup_ThemQuyenVaoGCN(string data, QUYENTRENGCN iSQuyen, THUATHEO thuaTheo)
        {
            bool success = false;
            string message = "";
            try
            {
                List<string> dSID = JsonConvert.DeserializeObject<List<string>>(data);
                BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
                if (iSQuyen == QUYENTRENGCN.QSDDAT)
                {
                    if (thuaTheo == THUATHEO.THUADATID)
                        success = DCGIAYCHUNGNHANServices.ThemQSDDatTheoThuaDatIDVaoGCN(dSID, bhs, out message);
                    else if (thuaTheo == THUATHEO.MDSDID)
                        success = DCGIAYCHUNGNHANServices.ThemQSDDatTheoMDSDIDVaoGCN(dSID, bhs, out message);
                }
                else if (iSQuyen == QUYENTRENGCN.QQLDAT)
                {
                    if (thuaTheo == THUATHEO.THUADATID)
                        success = DCGIAYCHUNGNHANServices.ThemQQLDatTheoThuaDatIDVaoGCN(dSID, bhs, out message);
                    else if (thuaTheo == THUATHEO.MDSDID)
                        success = DCGIAYCHUNGNHANServices.ThemQQLDatTheoMDSDIDVaoGCN(dSID, bhs, out message);
                }
                else if (iSQuyen == QUYENTRENGCN.QSHTS)
                {
                    success = DCGIAYCHUNGNHANServices.ThemQSHTSVaoGCN(dSID, bhs, out message);
                }
                if (success)

2.Modules/MPLIS.Modules.XuLyHoSo/Views/XLHSGiayChungNhan/_GiayChungNhan.cshtml
<div id="gcnnavtabID">
    <ul class="nav nav-tabs nav-justified">
        <li id="gcn-li1" class="active">
            <a id="gcnopenTab1" data-toggle="tab" href="#gcn-tabID">Thông tin giấy chứng nhận</a>
        </li>
        <li id="gcn-li2">
            <a id="gcnopenTab2" data-toggle="tab" href="#gcn-tabID">Thông tin nghĩa vụ tài chính</a>
        </li>
    </ul>
    <div id="gcn-tabs-cont" class="tab-content">
        <div id="gcn-tabID" class="tab-pane fade m-15 in active">
        </div>
    </div>
</div>

<div id="dialogformMAIN_SDDAT_Popup">
    @*@{Html.RenderPartial("_Popup_QUYENSDDAT");}*@
</div>
<div id="dialogformMAIN_SHTAISAN_Popup">
    @*@{Html.RenderPartial("_Popup_QUYENSHTAISAN");}*@
</div>
<div id="dialogformMAIN_CHU_Popup">
</div>
<script type="text/javascript">
    @*function LuuGiayChungNhan_MAIN_TTCHUNG() {
        //var xhlhs_gcnchon1 = $('#droplistxulyhsgcn').val();
        var formdatabanquet = new FormData();
        var fileInputbanquet = document.getElementById('chonfilebanquetid');
        if (fileInputbanquet.files.length > 0) {
            formdatabanquet.append(fileInputbanquet.files[0].name, fileInputbanquet.files[0]);
            var xhr = new XMLHttpRequest();
            xhr.open('POST', '@(Url.Action("ImportBanQuet", "XLHSGiayChungNhan"))');
            xhr.send(formdatabanquet);
        };
        var formGiayChungNhan_MAIN_TTCHUNG = $('#FormGCN_Main_TTCHUNGID');
        $.ajax({
            type: "POST",
            url: "/XLHSGiayChungNhan/Save_GCN_MAIN_TTCHUNG",
            data: formGiayChungNhan_MAIN_TTCHUNG.serialize(),
            success: function (html) {
                alert("Lưu thông tin GCN thành công");
            },
        });
    };*@
    $(document).ready(function () {
        $('#xlhsnavtabID .nav-tabs li').removeClass('active');
        $('#bhs-li4').removeClass('disabled');
        $('#bhs-li4').addClass('active');
        $('#gcnopenTab1').on('click', function () {
            $('#gcn-tabID').load('/XLHSGiayChungNhan/_GiayChungNhan_Main');
        });
        $('#gcnopenTab2').on("click", function () {
            console.log('Tab2 Click!');
        });
        $('#gcnopenTab1').click();
        $('#droplistxulyhsgcn').change(function () {
            var xhlhs_gcnchon = $('#droplistxulyhsgcn').val();
            $.ajax({
                type: "POST",
                url: "/XLHSGiayChungNhan/_GiayChungNhan_Main",
                data: { 'id_chon': xhlhs_gcnchon, },
                success: function (html) {
                    $('#divmainpanelID').html(html);
                },
            });
        });
    })
</script>

2.Modules/MPLIS.Modules.XuLyHoSo/Views/XLHSGiayChungNhan/_GiayChungNhan_Main.cshtml
@model MPLIS.Libraries.Data.XuLyHoSo.Models.BoHoSoModel
<div id="divGiayChungNhanID">
    <div class="row panel" style="margin-bottom: 5px;">
        <div class="btn btn-default btn-block tab-doc" style="text-align:left;">
            <a style="color: blue;font-weight: bold;" data-toggle="collapse" data-parent="#divGiayChungNhanID" href="#collapse_GCN_TTChung">
                Thông tin chung giấy chứng nhận
            </a>
            <button class="btn-xs btn-heading pull-right" type="button" onclick="LuuGiayChungNhan_MAIN_TTCHUNG()" @Html.Raw(Model.CurDC_GIAYCHUNGNHAN.ThuocDangKy ? "disabled" : "")>Cập nhật</button>
        </div>
        <div id="collapse_GCN_TTChung" class="panel-collapse collapse in">
            <div id="divGCN_TTChung_ID">
                @{Html.RenderPartial("_GiayChungNhan_Main_TTCHUNG");}
            </div>
        </div>
    </div>
    <div class="row panel" style="margin-bottom: 5px;">
        <div class="btn btn-default btn-block tab-doc" style="text-align:left;">
            <a style="color: blue;font-weight: bold;" data-toggle="collapse" data-parent="#divGiayChungNhanID" href="#collapse_GCN_SDDAT">
                Danh sách quyền sử dụng đất
            </a>
            <button class="btn-xs btn-heading pull-right" type="button" onclick="UpDateDSQuyenSDDat()" @Html.Raw(Model.CurDC_GIAYCHUNGNHAN.ThuocDangKy ? "disabled" : "")>Cập nhật</button>
            <button class="btn-xs btn-heading pull-right" type="button" onclick="GCN_ThemThuaDat('QSD')" @Html.Raw(Model.CurDC_GIAYCHUNGNHAN.ThuocDangKy ? "disabled" : "")>Thêm quyền</button>
        </div>
        <div id="collapse_GCN_SDDAT" class="panel-collapse collapse">
            <div id="divGCN_Main_SDDATID">
                @{Html.RenderPartial("_GiayChungNhan_Main_SDDAT");}
            </div>
        </div>
    </div>
    <div class="row panel" style="margin-bottom: 5px;">
        <div class="btn btn-default btn-block tab-doc" style="text-align:left;">
            <a style="color: blue;font-weight: bold;" data-toggle="collapse" data-parent="#divGiayChungNhanID" href="#collapse_GCN_SHTS">
                Danh sách quyền sở hữu tài sản
            </a>
            <button class="btn-xs btn-heading pull-right" type="button" onclick="UpDateDSQuyenSHTS()" @Html.Raw(Model.CurDC_GIAYCHUNGNHAN.ThuocDangKy ? "disabled" : "")>Cập nhật</button>
            <button class="btn-xs btn-heading pull-right" type="button" onclick="GCN_ThemTaiSan()" @Html.Raw(Model.CurDC_GIAYCHUNGNHAN.ThuocDangKy ? "disabled" : "")>Thêm tài sản</button>
        </div>
        <div id="collapse_GCN_SHTS" class="panel-collapse collapse">
            <div id="divGCN_Main_SHTaiSanID">
                @{Html.RenderPartial("_GiayChungNhan_Main_SHTAISAN");}
            </div>
        </div>
    </div>
    <div class="row panel" style="margin-bottom: 5px;">
        <div class="btn btn-default btn-block tab-doc" style="text-align:left;">
            <a style="color: blue;font-weight: bold;" data-toggle="collapse" data-parent="#divGiayChungNhanID" href="#collapse_GCN_QLD">
                Danh sách quyền quản lý đất
            </a>
            <button class="btn-xs btn-heading pull-right" type="button" onclick="UpDateDSQuyenQLDat()" @Html.Raw(Model.CurDC_GIAYCHUNGNHAN.ThuocDangKy ? "disabled" : "")>Cập nhật</button>
            <button class="btn-xs btn-heading pull-right" type="button" onclick="GCN_ThemThuaDat('QQL')" @Html.Raw(Model.CurDC_GIAYCHUNGNHAN.ThuocDangKy ? "disabled" : "")>Thêm quyền</button>
        </div>
        <div id="collapse_GCN_QLD" class="panel-collapse collapse">
            <div id="divGCN_Main_QLDATID">
                @{Html.RenderPartial("_GiayChungNhan_Main_QLDAT");}
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        trigger_tab_doc();
    })
    function LuuGiayChungNhan_MAIN_TTCHUNG() {
        //var xhlhs_gcnchon1 = $('#droplistxulyhsgcn').val();
        @*var formdatabanquet = new FormData();
        var fileInputbanquet = document.getElementById('chonfilebanquetid');
        if (fileInputbanquet.files.length > 0) {
            formdatabanquet.append(fileInputbanquet.files[0].name, fileInputbanquet.files[0]);
            var xhr = new XMLHttpRequest();
            xhr.open('POST', '@(Url.Action("ImportBanQuet", "XLHSGiayChungNhan"))');
            xhr.send(formdatabanquet);
        };*@
        $('#CurDC_GIAYCHUNGNHAN_TRANGTHAIXULY').removeAttr('disabled');
        var formGiayChungNhan_MAIN_TTCHUNG = $('#FormGCN_Main_TTCHUNGID');
        $.ajax({
            type: "POST",
            url: "/XLHSGiayChungNhan/Save_GCN_MAIN_TTCHUNG",
            data: formGiayChungNhan_MAIN_TTCHUNG.serialize(),
            success: function (html) {
                alert("Cập nhật thông tin GCN thành công!");
            },
        });
        $('#CurDC_GIAYCHUNGNHAN_TRANGTHAIXULY').attr('disabled', 'disabled');
    };
    function GCN_ThemThuaDat(isQuyen) {
        console.log(isQuyen);
        $.ajax({
            type: "POST",
            url: "/XLHSGiayChungNhan/_Popup_DSThuaTrongDK",
            data: { isQuyen: isQuyen },
            dataType: "html",
            success: function (html) {
                $('#dialogformMAIN_SDDAT_Popup')
                    .html(html)
                    .ready(function () {
                        var options = {
                            "backdrop": "static",
                            "show": true
                        }
                        $("#modalformDSThua").on('show.bs.modal', function () {
                            switch (isQuyen) {
                                case "QSD":
                                    $('#titlePopupQDID').html('Thêm quyền sử dụng đất vào giấy chứng nhận');
                                    break;
                                case "QQL":
                                    $('#titlePopupQDID').html('Thêm quyền quản lý đất vào giấy chứng nhận');
                                    break;
                                default:
                                    break;
                            }
                        });
                        $("#modalformDSThua").modal(options);
                    });
            }
        });
    };
    function GCN_ThemTaiSan() {
        $.ajax({
            type: "GET",
            url: "/XLHSGiayChungNhan/_Popup_DSTaiSanTrongDK",
            success: function (html) {
                $('#dialogformMAIN_SHTAISAN_Popup').html(html);
                var options = {
                    "backdrop": "static",
                    "show": true
                }
                $("#modalformDSTaiSan").modal(options);
            },
        });
    };
    function LuuGiayChungNhan_MAIN_SDDAT() {

    };
    function LuuGiayChungNhan_MAIN_SHTAISAN() {

    };

    function UpDateDSQuyenSDDat() {
        $.ajax({
            type: "POST",
            url: "/XLHSGiayChungNhan/updateDSQuyenSDDatInGCN",
            data: { gcnID: $('#CurDC_GIAYCHUNGNHAN_GIAYCHUNGNHANID').val() },
            success: function (html) {
                alert('Cập nhật danh sách quyền sử dụng đất thành công!');
            },
        });
    }

    function UpDateDSQuyenSHTS() {
        $.ajax({
            type: "POST",
            url: "/XLHSGiayChungNhan/updateDSQuyenSHTSInGCN",
            data: { gcnID: $('#CurDC_GIAYCHUNGNHAN_GIAYCHUNGNHANID').val() },
            success: function (html) {
                alert('Cập nhật danh sách quyền sở hữu tài sản thành công!');
            },
        })
    }

    function UpDateDSQuyenQLDat() {
        $.ajax({
            type: "POST",
            url: "/XLHSGiayChungNhan/updateDSQuyenQLDatInGCN",
            data: { gcnID: $('#CurDC_GIAYCHUNGNHAN_GIAYCHUNGNHANID').val() },
            success: function (html) {
                alert('Cập nhật danh sách quyền quản lý đất thành công!');
            },
        })
    }
</script>

2.Modules/MPLIS.Modules.XuLyHoSo/Views/XLHSGiayChungNhan/_GiayChungNhan_Main_SDDAT.cshtml
@model MPLIS.Libraries.Data.XuLyHoSo.Models.BoHoSoModel

<div class="box">
    <div class="box-body">
        <table id="_GCN_Main_SDDAT_TableID" class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Xã phường</th>
                    <th>SH tờ bản đồ</th>
                    <th>STT thửa</th>
                    <th>Mục đích sử dụng</th>
                    <th>Diện tích (m<sup>2</sup>)</th>
                    <th>Trạng thái</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.CurDC_GIAYCHUNGNHAN != null && Model.CurDC_GIAYCHUNGNHAN.DSQuyenSDDat != null && Model.CurDC_GIAYCHUNGNHAN.DSQuyenSDDat.Count > 0)
                {
                    int stt = 0;
                    foreach (var item in Model.CurDC_GIAYCHUNGNHAN.DSQuyenSDDat)
                    {
                        stt++;
                        <tr data-id="@item.QUYENSUDUNGDATID">
                            <td class="text-right">
                                @stt.
                            </td>
                            <td>
                                @item.XaPhuong
                            </td>
                            <td class="text-center">
                                @item.SHToBanDo
                            </td>
                            <td class="text-center">
                                @item.STTThua
                            </td>
                            <td class="text-center">
                                @item.MdsdDat.MDSD
                            </td>
                            <td class="text-center">
                                @item.DienTich
                            </td>
                            <td class="text-center">
                                @(item.TRANGTHAIPL == "T" ? "Đang thế chấp" : "Bình thường")
                            </td>
                            <td class="text-center">
                                @Ajax.ActionLink("Xóa", "Remove_DSQUYENSDDAT_Row", "XLHSGiayChungNhan", new { quyenSDDATID = item.QUYENSUDUNGDATID, gcnID = Model.CurDC_GIAYCHUNGNHAN.GIAYCHUNGNHANID },
                                new AjaxOptions
                                {
                                    HttpMethod = "POST",
                                    OnSuccess = "RemoveRow_GCN_Main_SDDAT_TableID",
                                    Confirm = "Xác nhận xóa?"
                                }, Model.CurDC_GIAYCHUNGNHAN.ThuocDangKy ? (object)new { @class = "btn btn-xs btn-heading", @title = "Xóa", @disabled = "" } : (object)new { @class = "btn btn-xs btn-heading", @title = "Xóa" })
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    var _GCN_Main_SDDAT_TableID;
    function RemoveRow_GCN_Main_SDDAT_TableID(objJson) {
        RemoveRowDataTable($('#_GCN_Main_SDDAT_TableID'), objJson.RowID);
    }
    $(document).ready(function () {
        _GCN_Main_SDDAT_TableID = InitDataTableXLHS($('#_GCN_Main_SDDAT_TableID'));
    });
</script>