2.Modules/MPLIS.Modules.XuLyHoSo/Controllers/XLHSDangKyController.cs
using MPLIS.Libraries.Data.XuLyHoSo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MPLIS.Libraries.Services.XuLyHoSo.Classes;
using AppCore.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AutoMapper;
using System.Collections;
using MPLIS.Web.FrameWork.Base;
using System.Data.Entity;
using MPLIS.Libraries.Data.XuLyHoSo.Models.XuLyHoSo.DangKy;

namespace MPLIS.Modules.XuLyHoSo.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.ReadOnly)]
    public class XLHSDangKyController : BaseController
    {

        #region Chủ trong đăng ký HieuVH2
        [HttpPost]
        public ActionResult Form_DanhSachChu()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            DSChuDonVM dSChuDonVM = new DSChuDonVM();
            foreach (var temp in bhs.HoSoTN.DonDangKy.DSDangKyChu)
                dSChuDonVM.DSDangKyChu.Add(Mapper.Map<DC_DANGKY_NGUOI, ChuDonVM>(temp));
            ViewBag.dSLoaiChu = DONDANGKYServices.GetDM_LOAICHU();
            return PartialView(dSChuDonVM);
        }
        [HttpPost]
        public ActionResult DanhSachChu_XoaChu(string dangKyNguoiID)
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            List<DC_DANGKY_NGUOI> dSDangKyChu = bhs.HoSoTN.DonDangKy.DSDangKyChu;
            bool success = false;
            string mes = "";
            if (DCDANGKYNGUOIServices.XoaChuTrongDangKy(dangKyNguoiID, dSDangKyChu, out mes))
            {
                success = true;
                Session["dSDangKyChu" + CurrentUser.UserName] = dSDangKyChu;
            }
            return Json(new { success = success, mes = mes });
        }
        [HttpPost]
        public ActionResult DanhSachChu_ThemMoiChu(string loaiChuID)
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            bhs.HoSoTN.DonDangKy.CurDangKyNguoi = new DC_DANGKY_NGUOI();
            DC_DANGKY_NGUOI dangKyNguoi = bhs.HoSoTN.DonDangKy.CurDangKyNguoi;
            dangKyNguoi.TRANGTHAI = 1;
            dangKyNguoi.DANGKYNGUOIID = Guid.NewGuid().ToString();
            dangKyNguoi.DONDANGKYID = bhs.HoSoTN.DonDangKy.DONDANGKYID;
            dangKyNguoi.ThemMoiChu(loaiChuID);
            DangKy_NguoiLS dangKyNguoiLS = Mapper.Map<DC_DANGKY_NGUOI, DangKy_NguoiLS>(dangKyNguoi);
            ViewBag.dSGioiTinh = DONDANGKYServices.GetDM_GIOITINH();
            ViewBag.dSDanToc = DONDANGKYServices.GetDM_DANTOC();
            ViewBag.dSQuocTich = DONDANGKYServices.GetDM_QUOCTICH();
            ViewBag.dSGiayToTuyThan = DONDANGKYServices.GetDM_LOAIGIAYTOTUYTHAN();
            ViewBag.dSDoiTuongSuDung = DONDANGKYServices.GetDM_DOITUONGSUDUNG(dangKyNguoi.LOAI ?? 0M);
            ViewBag.dSLoaiChuNhomNguoi = DONDANGKYServices.GetDM_LOAICHUNHOMNGUOI();
            Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return PartialView("DanhSachChu_ChiTietChu", dangKyNguoiLS);
        }
        [HttpPost]
        public ActionResult DanhSachChu_ChiTietChu(string dangKyNguoiID)
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            List<DC_DANGKY_NGUOI> dSDangKyChu = bhs.HoSoTN.DonDangKy.DSDangKyChu;
            bhs.HoSoTN.DonDangKy.CurDangKyNguoi = null;
            foreach (var temp in dSDangKyChu)
            {
                if (temp.DANGKYNGUOIID == dangKyNguoiID)
                {
                    temp.TRANGTHAI = 2;
                    temp.Chu.TRANGTHAI = 2;
                    bhs.HoSoTN.DonDangKy.CurDangKyNguoi = Mapper.Map<DC_DANGKY_NGUOI, DC_DANGKY_NGUOI>(temp);
                    break;
                }
            }
            DangKy_NguoiLS dangKyNguoiLS = Mapper.Map<DC_DANGKY_NGUOI, DangKy_NguoiLS>(bhs.HoSoTN.DonDangKy.CurDangKyNguoi);
            ViewBag.dSGioiTinh = DONDANGKYServices.GetDM_GIOITINH();
            ViewBag.dSDanToc = DONDANGKYServices.GetDM_DANTOC();
            ViewBag.dSQuocTich = DONDANGKYServices.GetDM_QUOCTICH();
            ViewBag.dSGiayToTuyThan = DONDANGKYServices.GetDM_LOAIGIAYTOTUYTHAN();
            ViewBag.dSDoiTuongSuDung = DONDANGKYServices.GetDM_DOITUONGSUDUNG(bhs.HoSoTN.DonDangKy.CurDangKyNguoi.LOAI ?? 0M);
            ViewBag.dSLoaiChuNhomNguoi = DONDANGKYServices.GetDM_LOAICHUNHOMNGUOI();
            Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return PartialView(dangKyNguoiLS);
        }
        [HttpPost]
        public ActionResult ChiTietChu_XoaTrang()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            string curLoaiChuID = bhs.HoSoTN.DonDangKy.CurDangKyNguoi.Chu.LOAIDOITUONGID;
            bhs.HoSoTN.DonDangKy.CurDangKyNguoi = null;
            bhs.HoSoTN.DonDangKy.CurDangKyNguoi = new DC_DANGKY_NGUOI();
            DC_DANGKY_NGUOI dangKyNguoi = bhs.HoSoTN.DonDangKy.CurDangKyNguoi;
            dangKyNguoi.TRANGTHAI = 1;
            dangKyNguoi.DANGKYNGUOIID = Guid.NewGuid().ToString();
            dangKyNguoi.DONDANGKYID = bhs.HoSoTN.DonDangKy.DONDANGKYID;
            dangKyNguoi.ThemMoiChu(curLoaiChuID);
            DangKy_NguoiLS dangKyNguoiLS = Mapper.Map<DC_DANGKY_NGUOI, DangKy_NguoiLS>(dangKyNguoi);
            ViewBag.dSGioiTinh = DONDANGKYServices.GetDM_GIOITINH();
            ViewBag.dSDanToc = DONDANGKYServices.GetDM_DANTOC();
            ViewBag.dSQuocTich = DONDANGKYServices.GetDM_QUOCTICH();
            ViewBag.dSGiayToTuyThan = DONDANGKYServices.GetDM_LOAIGIAYTOTUYTHAN();
            ViewBag.dSDoiTuongSuDung = DONDANGKYServices.GetDM_DOITUONGSUDUNG(dangKyNguoi.LOAI ?? 0M);
            ViewBag.dSLoaiChuNhomNguoi = DONDANGKYServices.GetDM_LOAICHUNHOMNGUOI();
            Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return PartialView("DanhSachChu_ChiTietChu", dangKyNguoiLS);
        }
        [HttpPost]
        public ActionResult Save_FormChiTietChu(string data)
        {
            bool success = false;
            string mes = "";
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            List<DC_DANGKY_NGUOI> dSDangKyNguoi = bhs.HoSoTN.DonDangKy.DSDangKyChu;
            DC_DANGKY_NGUOI dangKyNguoi = bhs.HoSoTN.DonDangKy.CurDangKyNguoi;
            NguoiLS nguoiLS = JsonConvert.DeserializeObject<NguoiLS>(data);
            DC_NGUOI nguoi = Mapper.Map<NguoiLS, DC_NGUOI>(nguoiLS);
            switch (dangKyNguoi.Chu.LOAIDOITUONGID)
            {
                case "1":
                    dangKyNguoi.Chu = nguoi;
                    dangKyNguoi.Chu.CaNhan = nguoi.CaNhan;
                    break;
                case "2":
                    nguoi.HoGiaDinh.DSThanhVien = Mapper.Map<List<DC_HOGIADINH_THANHVIEN>, List<DC_HOGIADINH_THANHVIEN>>(dangKyNguoi.Chu.HoGiaDinh.DSThanhVien);
                    dangKyNguoi.Chu = nguoi;
                    dangKyNguoi.Chu.HoGiaDinh.SetThongTinHoGiaDinh();
                    break;
                case "3":
                    nguoi.VoChong.ChongCN = dangKyNguoi.Chu.VoChong.ChongCN;
                    nguoi.VoChong.VoCN = dangKyNguoi.Chu.VoChong.VoCN;
                    dangKyNguoi.Chu = nguoi;
                    break;
                case "4":
                    nguoi.ToChuc.NguoiDaiDien = dangKyNguoi.Chu.ToChuc.NguoiDaiDien;
                    dangKyNguoi.Chu = nguoi;
                    break;
                case "5":
                    nguoi.CongDong.NguoiDaiDien = dangKyNguoi.Chu.CongDong.NguoiDaiDien;
                    dangKyNguoi.Chu = nguoi;
                    break;
                case "6":
                    nguoi.NhomNguoi.DSThanhVien = dangKyNguoi.Chu.NhomNguoi.DSThanhVien;
                    dangKyNguoi.Chu = nguoi;
                    break;
                default:
                    break;
            }
            success = DCDANGKYNGUOIServices.SaveDangKyNguoi(dangKyNguoi, dSDangKyNguoi, out mes);
            Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return Json(new { success = success, mes = mes, obj = new { LOAI = dangKyNguoi.LOAI, DANGKYNGUOIID = dangKyNguoi.DANGKYNGUOIID, TENLOAICHU = dangKyNguoi.Chu_TenLoaiChu, TENCHU = dangKyNguoi.Chu_HoTen, CMT = dangKyNguoi.Chu_CMT } });
        }
        #region Hộ Gia Đình
        [HttpPost]
        public ActionResult HoGiaDinh_ThemMoiThanhVien()
        {
            BoHoSoModel bhs = (BoHoSoModel)Session["BoHoSo_" + CurrentUser.UserName];
            DC_HOGIADINH hoGiaDinh = bhs.HoSoTN.DonDangKy.CurDangKyNguoi.Chu.HoGiaDinh;
            hoGiaDinh.CurHGDThanhVien = null;
            hoGiaDinh.CurHGDThanhVien = new DC_HOGIADINH_THANHVIEN();
            DC_HOGIADINH_THANHVIEN hoGiaDinhThanhVien = hoGiaDinh.CurHGDThanhVien;
            hoGiaDinhThanhVien.HOGIADINHTVID = Guid.NewGuid().ToString();
            hoGiaDinhThanhVien.TRANGTHAI = 1;
            hoGiaDinhThanhVien.ThanhVien = new DC_CANHAN();
            DC_CANHAN thanhVien = hoGiaDinhThanhVien.ThanhVien;
            thanhVien.CANHANID = Guid.NewGuid().ToString();
            thanhVien.TRANGTHAI = 1;
            hoGiaDinhThanhVien.CANHANID = thanhVien.CANHANID;
            hoGiaDinhThanhVien.HOGIADINHID = hoGiaDinh.HOGIADINHID;
            ViewBag.dSGioiTinh = DONDANGKYServices.GetDM_GIOITINH();
            ViewBag.dSDanToc = DONDANGKYServices.GetDM_DANTOC();
            ViewBag.dSQuocTich = DONDANGKYServices.GetDM_QUOCTICH();
            ViewBag.dSGiayToTuyThan = DONDANGKYServices.GetDM_LOAIGIAYTOTUYTHAN();
            ViewBag.dSQuanHe = DONDANGKYServices.GetDM_QHVOICHUHO();
            Session["BoHoSo_" + CurrentUser.UserName] = bhs;
            return PartialView("HoGiaDinh_ChiTietThanhVien", Mapper.Map<DC_HOGIADINH_THANHVIEN, HoGiaDinhThanhVienLS>(hoGiaDinhThanhVien));
        }
        [HttpPost]
        public ActionResult HoGiaDinh_ChiTietThanhVien(string hoGiaDinhTVID)
        {

2.Modules/MPLIS.Modules.XuLyHoSo/Views/XLHSDangKy/DonDangKy_DSThua_ChiTietGiaDat.cshtml
@using AppCore.Models
@model DC_THUADAT
    <form id="ChiTietGiaDat">
        @Html.HiddenFor(m => m.CurGiaDat.THUADATID, new { @class = "form-control" })
        @Html.HiddenFor(m => m.CurGiaDat.GIATHUADATID, new { @class = "form-control" })
        <div class="row">
            <div class="col-xs-4">
                @Html.LabelFor(model => model.CurGiaDat.LOAIGIADATID, "Loại giá đất", new { @class = "pull-right control-label" })
            </div>
            <div class="col-xs-8">
                @Html.DropDownListFor(model => model.CurGiaDat.LOAIGIADATID, new SelectList(ViewBag.loaigiadat, "LOAIGIADATID", "LOAIGIADAT"), new { @class = "form-control input-sm" })
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                @Html.LabelFor(model => model.CurGiaDat.CANCUPHAPLY, "Căn cứ pháp lý", new { @class = "pull-right control-label" })
            </div>
            <div class="col-xs-8">
                @Html.TextBoxFor(model => model.CurGiaDat.CANCUPHAPLY, new { @class = "form-control input-sm" })
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                @Html.LabelFor(model => model.CurGiaDat.THOIDIEMXACDINH, "Thời điểm", new { @class = "pull-right control-label" })
            </div>
            <div class="col-xs-8">
                @Html.TextBoxFor(model => model.CurGiaDat.THOIDIEMXACDINH, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control input-sm date" })
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                @Html.LabelFor(model => model.CurGiaDat.GIADAT, "Giá đất", new { @class = "pull-right control-label" })
            </div>
            <div class="col-xs-8">
                @Html.TextBoxFor(model => model.CurGiaDat.GIADAT, new { @class = "form-control input-sm" })
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                @Html.LabelFor(model => model.CurGiaDat.TENFILE, "Tên tệp tin", new { @class = "pull-right control-label" })
            </div>
            <div class="col-xs-8">
                @Html.TextBoxFor(model => model.CurGiaDat.TENFILE, new { @class = "form-control input-sm" })
            </div>
        </div>
    </form>

<script>

</script>

2.Modules/MPLIS.Modules.XuLyHoSo/Views/XLHSDangKy/Popup_DiaChiTaiSan.cshtml
@using AppCore.Models
@model AppCore.Models.DC_DIACHI
<div class='modal fade' id='modalformDiaChi'>
    <div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-header'>
                <button type='button' class='close' data-dismiss='modal'>&times;</button>
                <h4 class='modal-title' id="title_popup_diachi">Địa chỉ</h4>
            </div>
            <div class='modal-body' id="modalformDiaChi_body">
                @Html.Partial("_ChiTietDiaChi")
            </div>
            <div class='modal-footer' style='text-align:center;'>
                <button type='submit' id="btnthemdiachi" class='t100 btn btn-primary btn-sm pull-right'>Lưu</button>
                <button type='submit' id="btnlammoidiachi" class='t100 btn btn-primary btn-sm pull-left'>Làm mới</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#btnthemdiachi').on("click", function () {
            $('#drpxa').prop("disabled", false);
            $('#drphuyen').prop("disabled", false);
            var formdata = $('#pop_up_themdiachi').serializeArray();
            $.ajax({
                type: "POST",
                url: "/XLHSDangKy/ThemDiaChi",
                data: formdata,
                success: function (data) {
                    if ($("#drpchontaisan").val() == "1") {
                        $('#CurNhaRiengLe_DIACHI').html(data);
                    }
                    else if ($("#drpchontaisan").val() == "4") {
                    }
                    else if ($("#drpchontaisan").val() == "6") {
                        $('#CurCongTrinhXayDung_DIACHI').html(data);
                    }
                    else if ($("#drpchontaisan").val() == "7") {
                        $('#CurCongTrinhNgam_DIACHI').html(data);
                    }
                    else if ($("#drpchontaisan").val() == "8") {
                        $('#CurHangMucCongTrinh_DIACHIID').html(data);
                    }
                    else if ($("#drpchontaisan").val() == "9") {
                        $('#CurRungTrong_DIACHI').html(data);
                    }
                    else if ($("#drpchontaisan").val() == "10") {
                        $('#CurCayLauNam_DIACHI').html(data);
                    }
                }
            });
        });
        $('#btnlammoidiachi').on("click", function () {
            $.ajax({
                type: "GET",
                url: "/XLHSDangKy/LoadDiaChi",
                success: function (html) {
                    $('#modalformDiaChi_body').html(html);
                }
            });
        });
    });
</script>

2.Modules/MPLIS.Modules.XuLyHoSo/Views/XLHSDangKy/_DonDangKy_CONGTRINHXAYDUNG.cshtml
@using AppCore.Models
@model AppCore.Models.DangKyTaiSan
@{using (Html.BeginForm("_DonDangKy_TSNHARIENGLE", "XLHSDangKy", FormMethod.Post, new { @id = "ThemMoiCongTrinhXayDung" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.CurCongTrinhXayDung.CONGTRINHXAYDUNGID)
        @Html.HiddenFor(m => m.CurCongTrinhXayDung.uId)

        <div class="row">
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model=>Model.CurCongTrinhXayDung.TENCONGTRINH,"Tên công trình", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.TENCONGTRINH, new { @class = "form-control input-sm" })
                </div>
            </div>
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model => Model.tenxats, "Tên xã/phường", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.tenxats, new { @class = "form-control input-sm", @readonly = "true" })
                </div>
            </div>

        </div>
        <div class="row">
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model=>Model.CurCongTrinhXayDung.DIENTICHXAYDUNG,"Diện tích xây dựng", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.DIENTICHXAYDUNG, new { @class = "form-control input-sm" })
                </div>
            </div>
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model=>Model.CurCongTrinhXayDung.DIENTICHSAN,"Diện tích xây sàn", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.DIENTICHSAN, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>
        <div class="row">
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model=>Model.CurCongTrinhXayDung.NAMXAYDUNG,"Năm xây dựng", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.NAMXAYDUNG, new { @class = "form-control input-sm" })
                </div>
            </div>
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model=>Model.CurCongTrinhXayDung.NAMHOANTHANH,"Năm hoàn thành", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.NAMHOANTHANH, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>
        <div class="row">
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model=>Model.CurCongTrinhXayDung.HINHTHUCSOHUU,"Hình thức sở hữu", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.HINHTHUCSOHUU, new { @class = "form-control input-sm" })
                </div>
            </div>
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model=>Model.CurCongTrinhXayDung.THOIHANSOHUU,"Thời hạn sở hữu", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.THOIHANSOHUU, new { @class = "form-control input-sm" })
                </div>
            </div>

        </div>
        <div class="row">
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model => Model.CurCongTrinhXayDung.SOTANG, "Số tầng", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.SOTANG, new { @class = "form-control input-sm" })
                </div>
            </div>
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model => Model.CurCongTrinhXayDung.SOTANGHAM, "Số tầng hầm", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.SOTANGHAM, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>
        <div class="row">
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model => Model.CurCongTrinhXayDung.CAPHANG, "Cấp hạng", new { @class = "pull-right control-label" })
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(m => m.CurCongTrinhXayDung.CAPHANG, new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                @Html.LabelFor(m => m.mota, "Mô tả", new { @class = "pull-right control-label" })
            </div>
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.mota, new { @class = "form-control input-sm " })
            </div>
        </div>
        <div class="row">
            <div>
                <div class="col-xs-3">
                    @Html.LabelFor(Model=>Model.CurCongTrinhXayDung.DIACHI,"Địa chỉ",new { @class="pull-right control-label"})
                </div>
                <div class="col-xs-9">
                    @Html.TextAreaFor(Model=>Model.CurCongTrinhXayDung.DIACHI,new { @class="form-control input-sm",@row="2"})
                </div>
            </div>
        </div>
        <div class="clear"></div>
    }
}
<script>
    $(function () {
        // thêm mới nhà riêng lẻ

        $("#btnthemcongtrinh").on('click', function () {
            // alert($('#CurNhaRiengLe_KETCAU').val());
            var dondk = $('#DONDANGKYID').val();
            $.ajax({
                type: "POST",
                url: "/XLHSDangKy/LuuCongTrinh",
                data: { id: $('#CurCongTrinhXayDung_CONGTRINHXAYDUNGID').val(), tencongtrinh: $('#CurCongTrinhXayDung_TENCONGTRINH').val(), caphang: $('#CurCongTrinhXayDung_CAPHANG').val(), dientichxd: $('#CurCongTrinhXayDung_DIENTICHXAYDUNG').val(), dientichsan: $('#CurCongTrinhXayDung_DIENTICHSAN').val(), sotang: $('#CurCongTrinhXayDung_SOTANG').val(), sotangham: $('#CurCongTrinhXayDung_SOTANGHAM').val(), namxaydung: $('#CurCongTrinhXayDung_NAMXAYDUNG').val(), namhoanthanh: $('#CurCongTrinhXayDung_NAMHOANTHANH').val(), hinhthuc: $('#CurCongTrinhXayDung_HINHTHUCSOHUU').val(), thoihan: $('#CurCongTrinhXayDung_THOIHANSOHUU').val(), dondangkyid: dondk, taisanganvoidatid: $('#CurNhaRiengLe_uId').val() },
                dataType: "html",
                success: function (data) {
                    //alert(data);
                    $('#divdscongtrinh').html(data);
                    alert('lưu thành công!!!');
                    $('#CurCongTrinhXayDung_CONGTRINHXAYDUNGID').val(data.CurCongTrinhXayDung.CONGTRINHXAYDUNGID);
                   // alert(data.CurNhaRiengLe.NHARIENGLEID);
                    //$("#btnlammoinhariengle").click();
                }
            });
        });
        // làm mới nhà riêng lẻ
        $("#btnlammoicongtrinh").on('click', function () {
            $('#CurCongTrinhXayDung_CONGTRINHXAYDUNGID').val('');
            $('#CurCongTrinhXayDung_TENCONGTRINH').val('');
            $('#CurCongTrinhXayDung_CAPHANG').val('');
            $('#CurCongTrinhXayDung_DIENTICHXAYDUNG').val('');
            $('#CurCongTrinhXayDung_DIENTICHSAN').val('');
            $('#CurCongTrinhXayDung_SOTANG').val('');
            $('#CurCongTrinhXayDung_SOTANGHAM').val('');
            $('#CurCongTrinhXayDung_NAMXAYDUNG').val('');

            $('#CurCongTrinhXayDung_NAMHOANTHANH').val('');
            $('#CurCongTrinhXayDung_HINHTHUCSOHUU').val('');
            $('#CurCongTrinhXayDung_THOIHANSOHUU').val('');

            $('#CurCongTrinhXayDung_uId').val('');
        });
    });

</script>